### ISSUE TITLE
OSError: Could not find lib c or load any of its variants []

### ISSUE THREAD

**Issue by jakeeegarcia-alb** [conda-forge/shapely-feedstock#54]
Issue:

After executing this line ```from shapely.geometry import Line``` I get issues on this 

OSError: Could not find lib c or load any of its variants []. 

So, I created a new environment in anaconda and set priority to conda-forge so that I wouldn't be mixing packages from different channels as mentioned here:  https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it

However, as I install geopandas and run this line in the interpreter, 
```
from shapely.geometry import Line
```
the same error comes out.

- I have tried this: https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it as mentioned in another thread here.

- I tried setting this: export DYLD_FALLBACK_LIBRARY_PATH=$(HOME)/lib:/usr/local/lib:/lib:/usr/lib 

Also, I have no other geos installed in my system via homebrew or macports 

**`brew list`**

```
(base) Jacobs-MacBook-Pro:~ jacob$ brew list
apr		grib2		libmpc		netcdf		sqlite
apr-util	hdf5		libsodium	openssl		subversion
cmake		inetutils	libunistring	perl		szip
gcc		isl		lz4		proj		utf8proc
gdbm		jpeg		mpfr		python		wget
gettext		libidn		mpich		readline	xz
gmp		libidn2		mpich3		spatialindex	zeromq

(base) Jacobs-MacBook-Pro:~ jacob$ brew uninstall geos
Error: No such keg: /usr/local/Cellar/geos
```

** `brew cask list` **

```
(base) Jacobs-MacBook-Pro:~ jacob$ brew cask list
java                                     xquartz
```

Steps done:

1. Create a new environment GIS
2. Set channel priority to conda-forge
3. installed geopandas
4. Tried executing ```from shapely.geometry import Line``` however, I still get the same error.

<br/>
Environment (<code>conda list</code>):
<details>

```
(GIS) bash-3.2$ conda list
# packages in environment at /Users/jacob/anaconda3/envs/GIS:
#
# Name                    Version                   Build  Channel
attrs                     19.1.0                     py_0    conda-forge
boost-cpp                 1.70.0               h75728bb_2    conda-forge
bzip2                     1.0.8                h01d97ff_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.16.0            he1c11cd_1002    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cfitsio                   3.470                h389770f_1    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
fiona                     1.8.6            py37h39889d8_4    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      2.4.2            py37h39889d8_4    conda-forge
geopandas                 0.5.1                      py_0    conda-forge
geos                      3.7.2                h6de7cb9_1    conda-forge
geotiff                   1.5.1                h83de174_2    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.58.3            h9d45998_1002    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.5          nompi_h0cbb7df_1100    conda-forge
icu                       64.2                 h6de7cb9_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.10            h6659575_1005    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0               11_openblas    conda-forge
libcblas                  3.8.0               11_openblas    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    8.0.0                         4    conda-forge
libcxxabi                 8.0.0                         4    conda-forge
libdap4                   3.20.2            hae55d67_1000    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgdal                   2.4.2                hf77bb78_4    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             hed7d534_1010    conda-forge
liblapack                 3.8.0               11_openblas    conda-forge
libnetcdf                 4.6.2             h1a02027_1002    conda-forge
libopenblas               0.3.6                hd44dcd8_6    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libpq                     11.5                 h756f0eb_0    conda-forge
libspatialindex           1.9.0                h6de7cb9_1    conda-forge
libspatialite             4.3.0a            he369b6e_1029    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libxml2                   2.9.9                h12c6b28_2    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.17.0           py37h6b0580a_0    conda-forge
openjpeg                  2.3.1                hc1feee7_0    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
pandas                    0.25.0           py37h86efe34_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pip                       19.2.1                   py37_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
poppler                   0.67.0               hd5eb092_7    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 h25afefd_0    conda-forge
proj4                     6.1.0                h2cc77ee_2    conda-forge
pyproj                    2.2.1            py37h804dea5_0    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
rtree                     0.8.3           py37h666c49c_1002    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
shapely                   1.6.4           py37h0567c5e_1006    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.29.0               hb7d70f7_0    conda-forge
tk                        8.6.9             h2573ce8_1002    conda-forge
tzcode                    2019a             h01d97ff_1002    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xerces-c                  3.2.2             hbda6038_1004    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h01d97ff_1005    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
active environment : GIS
    active env location : /Users/jacob/anaconda3/envs/GIS
            shell level : 2
       user config file : /Users/jacob/.condarc
 populated config files : /Users/jacob/.condarc
          conda version : 4.7.10
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/jacob/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jacob/anaconda3/pkgs
                          /Users/jacob/.conda/pkgs
       envs directories : /Users/jacob/anaconda3/envs
                          /Users/jacob/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info -s</code> ):
<details>

```
(GIS) bash-3.2$ conda info -s
sys.version: 3.7.3 (default, Mar 27 2019, 16:54:48) 
...
sys.prefix: /Users/jacob/anaconda3
sys.executable: /Users/jacob/anaconda3/bin/python
conda location: /Users/jacob/anaconda3/lib/python3.7/site-packages/conda
conda-build: /Users/jacob/anaconda3/bin/conda-build
conda-convert: /Users/jacob/anaconda3/bin/conda-convert
conda-debug: /Users/jacob/anaconda3/bin/conda-debug
conda-develop: /Users/jacob/anaconda3/bin/conda-develop
conda-env: /Users/jacob/anaconda3/bin/conda-env
conda-index: /Users/jacob/anaconda3/bin/conda-index
conda-inspect: /Users/jacob/anaconda3/bin/conda-inspect
conda-metapackage: /Users/jacob/anaconda3/bin/conda-metapackage
conda-render: /Users/jacob/anaconda3/bin/conda-render
conda-server: /Users/jacob/anaconda3/bin/conda-server
conda-skeleton: /Users/jacob/anaconda3/bin/conda-skeleton
conda-verify: /Users/jacob/anaconda3/bin/conda-verify
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: GIS
CONDA_EXE: /Users/jacob/anaconda3/bin/conda
CONDA_PREFIX: /Users/jacob/anaconda3/envs/GIS
CONDA_PREFIX_1: /Users/jacob/anaconda3
CONDA_PROMPT_MODIFIER: (GIS) 
CONDA_PYTHON_EXE: /Users/jacob/anaconda3/bin/python
CONDA_ROOT: /Users/jacob/anaconda3
CONDA_SHLVL: 2
PATH: /Users/jacob/anaconda3/bin:/Users/jacob/anaconda3/envs/GIS/bin:/Users/jacob/anaconda3/condabin:/usr/local/git/bin:/sw/bin:/usr/local/bin:/usr/local:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/Cellar/netcdf/4.6.3_1/bin:/usr/local/Cellar/mpich3/include:/usr/local/opt/python/libexec/bin:/Users/jacob/Desktop/WRF4/ncl/ncl_6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/opt/inetutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:/Users/jacob/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>

```
</details>

</details>

<br/>
Details about  <code>cat .condarc</code>:
<details>

```
`(GIS) bash-3.2$ cat .condarc
ssl_verify: true
channels:
  - conda-forge
  - defaults
channel_priority: strict`

```
</details>

The error from the python prompt is still the same:

`from shapely.geometry import Line`

```
Last login: Sat Aug 10 23:00:22 on ttys000
-bash: HOME: command not found
/Users/jacob/.anaconda/navigator/a.tool ; exit;
(base) Jacobs-MacBook-Pro:~ jacob$ /Users/jacob/.anaconda/navigator/a.tool ; exit;
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from shapely.geometry import Line
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jacob/anaconda3/envs/GIS/lib/python3.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Users/jacob/anaconda3/envs/GIS/lib/python3.7/site-packages/shapely/geometry/base.py", line 17, in <module>
    from shapely.coords import CoordinateSequence
  File "/Users/jacob/anaconda3/envs/GIS/lib/python3.7/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/Users/jacob/anaconda3/envs/GIS/lib/python3.7/site-packages/shapely/geos.py", line 113, in <module>
    free = load_dll('c').free
  File "/Users/jacob/anaconda3/envs/GIS/lib/python3.7/site-packages/shapely/geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants [].
```

List of files inside ../GIS/lib:
```
(base) Jacobs-MacBook-Pro:lib jacob$ pwd
/Users/jacob/anaconda3/envs/GIS/lib
(base) Jacobs-MacBook-Pro:lib jacob$ ls
GNU.Gettext.dll				libicui18n.dylib
Tk.icns					libicuio.64.2.dylib
Tk.tiff					libicuio.64.dylib
_int.so					libicuio.dylib
adminpack.so				libicutest.64.2.dylib
amcheck.so				libicutest.64.dylib
ascii_and_mic.so			libicutest.dylib
auth_delay.so				libicutu.64.2.dylib
auto_explain.so				libicutu.64.dylib
autoinc.so				libicutu.dylib
bloom.so				libicuuc.64.2.dylib
btree_gin.so				libicuuc.64.dylib
btree_gist.so				libicuuc.dylib
cairo					libintl.8.dylib
charset.alias				libintl.a
citext.so				libintl.dylib
cmake					libjpeg.9.dylib
cube.so					libjpeg.a
cyrillic_and_mic.so			libjpeg.dylib
dblink.so				libjson-c.4.dylib
dict_int.so				libjson-c.a
dict_snowball.so			libjson-c.dylib
dict_xsyn.so				libk5crypto.3.1.dylib
earthdistance.so			libk5crypto.3.dylib
engines-1.1				libk5crypto.dylib
euc2004_sjis2004.so			libkadm5clnt.dylib
euc_cn_and_mic.so			libkadm5clnt_mit.11.0.dylib
euc_jp_and_sjis.so			libkadm5clnt_mit.11.dylib
euc_kr_and_mic.so			libkadm5clnt_mit.dylib
euc_tw_and_big5.so			libkadm5srv.dylib
file_fdw.so				libkadm5srv_mit.11.0.dylib
fuzzystrmatch.so			libkadm5srv_mit.11.dylib
gettext					libkadm5srv_mit.dylib
girepository-1.0			libkdb5.9.0.dylib
glib-2.0				libkdb5.9.dylib
hstore.so				libkdb5.dylib
icu					libkea.1.4.10.dylib
insert_username.so			libkea.1.4.dylib
isn.so					libkea.dylib
itcl4.1.2				libkmlbase.1.3.0.dylib
krb5					libkmlbase.1.dylib
latin2_and_win1250.so			libkmlbase.dylib
latin_and_mic.so			libkmlconvenience.1.3.0.dylib
libasprintf.0.dylib			libkmlconvenience.1.dylib
libasprintf.a				libkmlconvenience.dylib
libasprintf.dylib			libkmldom.1.3.0.dylib
libblas.3.dylib				libkmldom.1.dylib
libblas.dylib				libkmldom.dylib
libboost_atomic.a			libkmlengine.1.3.0.dylib
libboost_atomic.dylib			libkmlengine.1.dylib
libboost_chrono.a			libkmlengine.dylib
libboost_chrono.dylib			libkmlregionator.1.3.0.dylib
libboost_container.a			libkmlregionator.1.dylib
libboost_container.dylib		libkmlregionator.dylib
libboost_context.a			libkmlxsd.1.3.0.dylib
libboost_context.dylib			libkmlxsd.1.dylib
libboost_contract.a			libkmlxsd.dylib
libboost_contract.dylib			libkrad.0.0.dylib
libboost_coroutine.a			libkrad.0.dylib
libboost_coroutine.dylib		libkrad.dylib
libboost_date_time.a			libkrb5.3.3.dylib
libboost_date_time.dylib		libkrb5.3.dylib
libboost_exception.a			libkrb5.dylib
libboost_fiber.a			libkrb5support.1.1.dylib
libboost_fiber.dylib			libkrb5support.1.dylib
libboost_filesystem.a			libkrb5support.dylib
libboost_filesystem.dylib		liblapack.3.dylib
libboost_graph.a			liblapack.dylib
libboost_graph.dylib			liblz4.1.8.3.dylib
libboost_iostreams.a			liblz4.1.dylib
libboost_iostreams.dylib		liblz4.a
libboost_locale.a			liblz4.dylib
libboost_locale.dylib			liblzma.5.dylib
libboost_log.a				liblzma.a
libboost_log.dylib			liblzma.dylib
libboost_log_setup.a			libmenu.6.dylib
libboost_log_setup.dylib		libmenu.a
libboost_math_c99.a			libmenu.dylib
libboost_math_c99.dylib			libmenuw.6.dylib
libboost_math_c99f.a			libmenuw.a
libboost_math_c99f.dylib		libmenuw.dylib
libboost_math_c99l.a			libmfhdf.0.dylib
libboost_math_c99l.dylib		libmfhdf.a
libboost_math_tr1.a			libmfhdf.dylib
libboost_math_tr1.dylib			libminizip.dylib
libboost_math_tr1f.a			libncurses++.a
libboost_math_tr1f.dylib		libncurses++w.a
libboost_math_tr1l.a			libncurses.6.dylib
libboost_math_tr1l.dylib		libncurses.a
libboost_prg_exec_monitor.a		libncurses.dylib
libboost_prg_exec_monitor.dylib		libncursesw.6.dylib
libboost_program_options.a		libncursesw.a
libboost_program_options.dylib		libncursesw.dylib
libboost_random.a			libnetcdf.13.dylib
libboost_random.dylib			libnetcdf.a
libboost_regex.a			libnetcdf.dylib
libboost_regex.dylib			libnetcdf.settings
libboost_serialization.a		libopenblas.0.dylib
libboost_serialization.dylib		libopenblasp-r0.3.6.dylib
libboost_stacktrace_addr2line.a		libopenjp2.2.3.1.dylib
libboost_stacktrace_addr2line.dylib	libopenjp2.7.dylib
libboost_stacktrace_basic.a		libopenjp2.a
libboost_stacktrace_basic.dylib		libopenjp2.dylib
libboost_stacktrace_noop.a		libpanel.6.dylib
libboost_stacktrace_noop.dylib		libpanel.a
libboost_system.a			libpanel.dylib
libboost_system.dylib			libpanelw.6.dylib
libboost_test_exec_monitor.a		libpanelw.a
libboost_thread.a			libpanelw.dylib
libboost_thread.dylib			libpcre.1.dylib
libboost_timer.a			libpcre.a
libboost_timer.dylib			libpcre.dylib
libboost_type_erasure.a			libpcrecpp.0.dylib
libboost_type_erasure.dylib		libpcrecpp.a
libboost_unit_test_framework.a		libpcrecpp.dylib
libboost_unit_test_framework.dylib	libpcreposix.0.dylib
libboost_wave.a				libpcreposix.a
libboost_wave.dylib			libpcreposix.dylib
libboost_wserialization.a		libpgcommon.a
libboost_wserialization.dylib		libpgfeutils.a
libbz2.1.0.8.dylib			libpgport.a
libbz2.a				libpgtypes.3.11.dylib
libbz2.dylib				libpgtypes.3.dylib
libc++.1.0.dylib			libpgtypes.a
libc++.1.dylib				libpgtypes.dylib
libc++.a				libpixman-1.0.dylib
libc++.dylib				libpixman-1.a
libc++abi.1.0.dylib			libpixman-1.dylib
libc++abi.1.dylib			libpng.a
libc++abi.a				libpng.dylib
libc++abi.dylib				libpng16.16.dylib
libc++experimental.a			libpng16.a
libc++fs.a				libpng16.dylib
libcairo-gobject.2.dylib		libpoppler-cpp.0.5.0.dylib
libcairo-gobject.a			libpoppler-cpp.0.dylib
libcairo-gobject.dylib			libpoppler-cpp.dylib
libcairo-script-interpreter.2.dylib	libpoppler-glib.8.9.0.dylib
libcairo-script-interpreter.a		libpoppler-glib.8.dylib
libcairo-script-interpreter.dylib	libpoppler-glib.dylib
libcairo.2.dylib			libpoppler.78.0.0.dylib
libcairo.a				libpoppler.78.dylib
libcairo.dylib				libpoppler.dylib
libcblas.3.dylib			libpq.5.11.dylib
libcblas.dylib				libpq.5.dylib
libcfitsio.8.3.47.dylib			libpq.a
libcfitsio.8.dylib			libpq.dylib
libcfitsio.a				libpqwalreceiver.so
libcfitsio.dylib			libproj.15.dylib
libcharset.1.dylib			libproj.a
libcharset.a				libproj.dylib
libcharset.dylib			libpython3.7m.a
libcom_err.3.0.dylib			libpython3.7m.dylib
libcom_err.3.dylib			libquadmath.0.dylib
libcom_err.dylib			libquadmath.dylib
libcrypto.1.1.dylib			libreadline.8.0.dylib
libcrypto.dylib				libreadline.8.dylib
libcurl.4.dylib				libreadline.a
libcurl.a				libreadline.dylib
libcurl.dylib				libspatialindex.5.0.0.dylib
libdap.25.dylib				libspatialindex.5.dylib
libdap.a				libspatialindex.dylib
libdap.dylib				libspatialindex_c.5.0.0.dylib
libdapclient.6.dylib			libspatialindex_c.5.dylib
libdapclient.a				libspatialindex_c.dylib
libdapclient.dylib			libspatialite.7.dylib
libdapserver.7.dylib			libspatialite.dylib
libdapserver.a				libsqlite3.0.dylib
libdapserver.dylib			libsqlite3.a
libdf.0.dylib				libsqlite3.dylib
libdf.a					libssh2.1.0.1.dylib
libdf.dylib				libssh2.1.dylib
libecpg.6.11.dylib			libssh2.a
libecpg.6.dylib				libssh2.dylib
libecpg.a				libssl.1.1.dylib
libecpg.dylib				libssl.dylib
libecpg_compat.3.11.dylib		libtcl8.6.dylib
libecpg_compat.3.dylib			libtclstub8.6.a
libecpg_compat.a			libtest-types.a
libecpg_compat.dylib			libtiff.5.dylib
libedit.0.dylib				libtiff.a
libedit.a				libtiff.dylib
libedit.dylib				libtiffxx.5.dylib
libexpat.1.6.7.dylib			libtiffxx.a
libexpat.1.dylib			libtiffxx.dylib
libexpat.a				libtinfo.6.dylib
libexpat.dylib				libtinfo.a
libffi.6.dylib				libtinfo.dylib
libffi.a				libtinfow.6.dylib
libffi.dylib				libtinfow.a
libfontconfig.1.dylib			libtinfow.dylib
libfontconfig.a				libtk8.6.dylib
libfontconfig.dylib			libtkstub8.6.a
libform.6.dylib				libtz.a
libform.a				liburiparser.dylib
libform.dylib				libverto.0.0.dylib
libformw.6.dylib			libverto.0.dylib
libformw.a				libverto.dylib
libformw.dylib				libxerces-c-3.2.dylib
libfreetype.6.dylib			libxerces-c.dylib
libfreetype.a				libxml2.2.dylib
libfreetype.dylib			libxml2.dylib
libfreexl.1.dylib			libz.1.2.11.dylib
libfreexl.a				libz.1.dylib
libfreexl.dylib				libz.a
libgcc_s.1.dylib			libz.dylib
libgcc_s_ppc64.1.dylib			libzstd.1.4.0.dylib
libgcc_s_x86_64.1.dylib			libzstd.1.dylib
libgdal.20.dylib			libzstd.a
libgdal.a				libzstd.dylib
libgdal.dylib				lo.so
libgeos-3.7.2.dylib			ltree.so
libgeos.dylib				mod_spatialite.7.so
libgeos_c.1.dylib			mod_spatialite.so
libgeos_c.dylib				moddatetime.so
libgeotiff.5.0.0.dylib			openjpeg-2.3
libgeotiff.5.dylib			pageinspect.so
libgeotiff.dylib			passwordcheck.so
libgettextlib-0.19.8.1.dylib		pg_buffercache.so
libgettextlib.dylib			pg_freespacemap.so
libgettextpo.0.dylib			pg_prewarm.so
libgettextpo.a				pg_stat_statements.so
libgettextpo.dylib			pg_trgm.so
libgettextsrc-0.19.8.1.dylib		pg_visibility.so
libgettextsrc.dylib			pgcrypto.so
libgfortran.3.dylib			pgoutput.so
libgfortran.dylib			pgrowlocks.so
libgif.a				pgstattuple.so
libgif.so				pgxml.so
libgif.so.7				pgxs
libgif.so.7.1.0				pkgconfig
libgio-2.0.0.dylib			plpgsql.so
libgio-2.0.dylib			postgres_fdw.so
libglib-2.0.0.dylib			python3.7
libglib-2.0.dylib			refint.so
libgmodule-2.0.0.dylib			seg.so
libgmodule-2.0.dylib			sqlite3.25.3
libgobject-2.0.0.dylib			sslinfo.so
libgobject-2.0.dylib			tablefunc.so
libgomp.1.dylib				tcl8
libgomp.dylib				tcl8.6
libgssapi_krb5.2.2.dylib		tclConfig.sh
libgssapi_krb5.2.dylib			tclooConfig.sh
libgssapi_krb5.dylib			tcn.so
libgssrpc.4.2.dylib			tdbc1.1.0
libgssrpc.4.dylib			tdbcmysql1.1.0
libgssrpc.dylib				tdbcodbc1.1.0
libgthread-2.0.0.dylib			tdbcpostgres1.1.0
libgthread-2.0.dylib			terminfo
libhdf4.settings			terminfo.c~
libhdf5.103.dylib			test_decoding.so
libhdf5.a				thread2.8.4
libhdf5.dylib				timetravel.so
libhdf5.settings			tk8.6
libhdf5_cpp.103.dylib			tkConfig.sh
libhdf5_cpp.a				tsm_system_rows.so
libhdf5_cpp.dylib			tsm_system_time.so
libhdf5_fortran.a			unaccent.so
libhdf5_hl.100.dylib			utf8_and_ascii.so
libhdf5_hl.a				utf8_and_big5.so
libhdf5_hl.dylib			utf8_and_cyrillic.so
libhdf5_hl_cpp.100.dylib		utf8_and_euc2004.so
libhdf5_hl_cpp.a			utf8_and_euc_cn.so
libhdf5_hl_cpp.dylib			utf8_and_euc_jp.so
libhdf5_hl_fortran.a			utf8_and_euc_kr.so
libhdf5hl_fortran.a			utf8_and_euc_tw.so
libhistory.8.0.dylib			utf8_and_gb18030.so
libhistory.8.dylib			utf8_and_gbk.so
libhistory.a				utf8_and_iso8859.so
libhistory.dylib			utf8_and_iso8859_1.so
libiconv.2.dylib			utf8_and_johab.so
libiconv.a				utf8_and_sjis.so
libiconv.dylib				utf8_and_sjis2004.so
libicudata.64.2.dylib			utf8_and_uhc.so
libicudata.64.dylib			utf8_and_win.so
libicudata.dylib			uuid-ossp.so
libicui18n.64.2.dylib			xml2Conf.sh
libicui18n.64.dylib
```
I created a new environment and set conda-forge to priority and set this `conda config --set channel_priority strict`.  I am not sure why this is still happening.

I also made sure that there were no other geos versions installed in my system.

It seems that a lot of osx users come across this problem.

**Comment by ocefpaf** [comment]
Please do not open multiple issues. You already have #53 and it does not look like the problem is with the package.
