### ISSUE TITLE
OSError: Could not find lib geos_c.dll or load any of its variants

### ISSUE THREAD

**Issue by mullenkamp** [conda-forge/shapely-feedstock#55]
Issue:
When creating a new python environment via conda and attempting to import shapely, python throws the following error:

```
conda create -n geo1 python=3.6 shapely
```

```
>>> from shapely.geometry import shape, Point
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python\miniconda3_64bit\envs\geo1\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>

    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\python\miniconda3_64bit\envs\geo1\lib\site-packages\shapely\geometry\base.py", line 17, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\python\miniconda3_64bit\envs\geo1\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\python\miniconda3_64bit\envs\geo1\lib\site-packages\shapely\geos.py", line 130, in <module>
    os.path.join(sys.prefix, "Library", "lib", "geos_c.dll"),
  File "C:\python\miniconda3_64bit\envs\geo1\lib\site-packages\shapely\geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c.dll or load any of its variants ['C:\\python\\miniconda3_64bit\\envs\\geo1\\Library\\lib\\geos_c.dll'].
```

This occurs on new versions of conda as well as old (at least the couple that I've tried).
The interesting part is that the root environment works fine, but any new environments (as created above) does not work.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at C:\python\miniconda3_64bit\envs\geo1:
#
# Name                    Version                   Build  Channel
certifi                   2019.6.16                py36_1    conda-forge
geos                      3.7.2                he025d50_1    conda-forge
intel-openmp              2019.4                      245
libblas                   3.8.0                    12_mkl    conda-forge
libcblas                  3.8.0                    12_mkl    conda-forge
liblapack                 3.8.0                    12_mkl    conda-forge
mkl                       2019.4                      245
numpy                     1.17.2           py36hc71023c_0    conda-forge
pip                       19.2.3                   py36_0    conda-forge
python                    3.6.7             he025d50_1005    conda-forge
setuptools                41.2.0                   py36_0    conda-forge
shapely                   1.6.4           py36ha35856d_1006    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.33.6                   py36_0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : geo1
    active env location : C:\python\miniconda3_64bit\envs\geo1
            shell level : 2
       user config file : C:\Users\michaelek\.condarc
 populated config files : C:\Users\michaelek\.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : C:\python\miniconda3_64bit  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/mullenkamp/win-64
                          https://conda.anaconda.org/mullenkamp/noarch
          package cache : C:\python\miniconda3_64bit\pkgs
                          C:\Users\michaelek\.conda\pkgs
                          C:\Users\michaelek\AppData\Local\conda\conda\pkgs
       envs directories : C:\python\miniconda3_64bit\envs
                          C:\Users\michaelek\.conda\envs
                          C:\Users\michaelek\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

Might be similar to #45 

Thanks!

**Comment by mullenkamp** [comment]
I just tested it...shapely version 1.6.3 does work...
It uses an older version of geos...which might be the core issue here...
```
# packages in environment at C:\python\miniconda3_64bit\envs\geo1:
#
# Name                    Version                   Build  Channel
certifi                   2019.6.16                py36_1    conda-forge
geos                      3.6.2                h9ef7328_2
intel-openmp              2019.4                      245
libblas                   3.8.0                    12_mkl    conda-forge
libcblas                  3.8.0                    12_mkl    conda-forge
liblapack                 3.8.0                    12_mkl    conda-forge
mkl                       2019.4                      245
numpy                     1.17.2           py36hc71023c_0    conda-forge
pip                       19.2.3                   py36_0    conda-forge
python                    3.6.7             he025d50_1005    conda-forge
setuptools                41.2.0                   py36_0    conda-forge
shapely                   1.6.3                    py36_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.33.6                   py36_0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
```

**Comment by cswartzvi** [comment]
I am also experiencing this issue on windows with an environment created as described by the OP. I found the following with the logging module:

```
DEBUG:shapely.geos:Trying `CDLL(C:\Users\charles\AppData\Local\Continuum\miniconda3\envs\geo1\Library\bin\geos_c.dll)`
DEBUG:shapely.geos:Failed `CDLL(C:\Users\charles\AppData\Local\Continuum\miniconda3\envs\geo1\Library\bin\geos_c.dll)`
DEBUG:shapely.geos:Trying `CDLL(C:\Users\charles\AppData\Local\Continuum\miniconda3\envs\geo1\Library\lib\geos_c.dll)`
DEBUG:shapely.geos:Failed `CDLL(C:\Users\charles\AppData\Local\Continuum\miniconda3\envs\geo1\Library\lib\geos_c.dll)`
```
which appears to be generated from [this line](https://github.com/Toblerity/Shapely/blob/06f3ae39b92356bb8261e281b8e62603eb41e722/shapely/geos.py#L38). I have no idea why `CDLL` would fail.

Note: the first file, `Library\bin\geos_c.dll`, does exist, the second file, `Library\lib\geos_c.dll`, does not.

**Comment by robroc** [comment]
I recently updated geopandas and now I'm getting this error. When importing geopandas in Jupyter Lab, this alert pops up:

![Capture](https://user-images.githubusercontent.com/1219001/64643026-9571b100-d3dd-11e9-9f26-464958b41b8a.PNG)

Versions:
python 3.6.7
shapely==1.6.4
geopandas==0.5.1
fiona==1.8.6

Full error message:

```OSError                                   Traceback (most recent call last)
<ipython-input-1-15b06ff0c9eb> in <module>
      1 import pandas as pd
----> 2 import geopandas as gpd
      3 
      4 get_ipython().run_line_magic('matplotlib', 'inline')

~\AppData\Local\Continuum\miniconda3\envs\geo\lib\site-packages\geopandas\__init__.py in <module>
----> 1 from geopandas.geoseries import GeoSeries
      2 from geopandas.geodataframe import GeoDataFrame
      3 from geopandas.geodataframe import points_from_xy
      4 
      5 from geopandas.io.file import read_file

~\AppData\Local\Continuum\miniconda3\envs\geo\lib\site-packages\geopandas\geoseries.py in <module>
      6 from pandas import Series
      7 import pyproj
----> 8 from shapely.geometry import shape, Point
      9 from shapely.geometry.base import BaseGeometry
     10 from shapely.ops import transform

~\AppData\Local\Continuum\miniconda3\envs\geo\lib\site-packages\shapely\geometry\__init__.py in <module>
      2 """
      3 
----> 4 from .base import CAP_STYLE, JOIN_STYLE
      5 from .geo import box, shape, asShape, mapping
      6 from .point import Point, asPoint

~\AppData\Local\Continuum\miniconda3\envs\geo\lib\site-packages\shapely\geometry\base.py in <module>
     15 
     16 from shapely.affinity import affine_transform
---> 17 from shapely.coords import CoordinateSequence
     18 from shapely.errors import WKBReadingError, WKTReadingError
     19 from shapely.ftools import wraps

~\AppData\Local\Continuum\miniconda3\envs\geo\lib\site-packages\shapely\coords.py in <module>
      6 from ctypes import byref, c_double, c_uint
      7 
----> 8 from shapely.geos import lgeos
      9 from shapely.topology import Validating
     10 

~\AppData\Local\Continuum\miniconda3\envs\geo\lib\site-packages\shapely\geos.py in <module>
    128             (egg_dlls, wininst_dlls, original_path)
    129         _lgeos = load_dll("geos_c.dll", fallbacks=[
--> 130             os.path.join(sys.prefix, "Library", "lib", "geos_c.dll"),
    131         ])
    132     except (ImportError, WindowsError, OSError):

~\AppData\Local\Continuum\miniconda3\envs\geo\lib\site-packages\shapely\geos.py in load_dll(libname, fallbacks, mode)
     54         raise OSError(
     55             "Could not find lib {0} or load any of its variants {1}.".format(
---> 56                 libname, fallbacks or []))
     57 
     58 _lgeos = None

OSError: Could not find lib geos_c.dll or load any of its variants ['C:\\Users\\rochar\\AppData\\Local\\Continuum\\miniconda3\\envs\\geo\\Library\\lib\\geos_c.dll'].```

**Comment by ocefpaf** [comment]
I just tried:

```
conda create -n geo1 python=3.6 shapely --yes
conda activate geo1
python -c "import shapely; print(shapely.__version__)"
1.6.4.post2
```

and everything worked for me.

Here is my package list:
```
(geo1) conda list
# packages in environment at C:\Miniconda3\envs\geo1:
#
# Name                    Version                   Build  Channel
geos                      3.7.2                he025d50_1    conda-forge
intel-openmp              2019.4                      245    defaults
libblas                   3.8.0                    12_mkl    conda-forge
libcblas                  3.8.0                    12_mkl    conda-forge
liblapack                 3.8.0                    12_mkl    conda-forge
mkl                       2019.4                      245    defaults
numpy                     1.17.2           py36hc71023c_0    conda-forge
python                    3.6.7             he025d50_1005    conda-forge
shapely                   1.6.4           py36ha35856d_1006    conda-forge
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
```

You `geos` is coming from defaults and not conda-forge, which makes me think you are no using `strict`. See https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels and https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge

**Comment by mullenkamp** [comment]
If you look at my original post my goes definitely comes from conda-forge...where did you see the default?
I've seen this kind of problem before with these GIS packages and them not pulling through runtime files.
You're likely running linux and I'm running windows.

Please reopen this issue or I'll make another one...

**Comment by cswartzvi** [comment]
I would just like to echo @mullenkamp statement that the base import does not throw an error;
```
python -c "import shapely; print(shapely.__version__)"
1.6.4.post2
```

But any attempt to import from sub-modules dependent on `geos` (such as `geometry`) produce the original `OSError`: 
```
python -c "import shapely.geometry"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Charles\Software\Miniconda3\envs\geo01\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Users\Charles\Software\Miniconda3\envs\geo01\lib\site-packages\shapely\geometry\base.py", line 17, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Users\Charles\Software\Miniconda3\envs\geo01\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\Charles\Software\Miniconda3\envs\geo01\lib\site-packages\shapely\geos.py", line 130, in <module>
    os.path.join(sys.prefix, "Library", "lib", "geos_c.dll"),
  File "C:\Users\Charles\Software\Miniconda3\envs\geo01\lib\site-packages\shapely\geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c.dll or load any of its variants ['C:\\Users\\Charles\\Software\\Miniconda3\\envs\\geo01\\Library\\lib\\geos_c.dll'].
```

Here is my package listing (channel priority set to strict):
```
conda list
# packages in environment at C:\Users\Charles\Software\Miniconda3\envs\geo01:
#
# Name                    Version                   Build  Channel
certifi                   2019.9.11                py36_0    conda-forge
geos                      3.7.2                he025d50_1    conda-forge
intel-openmp              2019.4                      245
libblas                   3.8.0                    12_mkl    conda-forge
libcblas                  3.8.0                    12_mkl    conda-forge
liblapack                 3.8.0                    12_mkl    conda-forge
mkl                       2019.4                      245
numpy                     1.17.2           py36hc71023c_0    conda-forge
pip                       19.2.3                   py36_0    conda-forge
python                    3.6.7             he025d50_1005    conda-forge
setuptools                41.2.0                   py36_0    conda-forge
shapely                   1.6.4           py36ha35856d_1006    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.33.6                   py36_0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
```

One more piece of information, this exact same environment works without error on my workstation that had QGIS installed prior to the creation of the environment.

**Comment by robroc** [comment]
This made it work for me:

1. Install shapely via [wheel file from here](https://www.lfd.uci.edu/~gohlke/pythonlibs/).
2. Install everything else after.

**Comment by ocefpaf** [comment]
> If you look at my original post my geos definitely comes from conda-forge...where did you see the default?

See your own list in https://github.com/conda-forge/shapely-feedstock/issues/55#issuecomment-529308668

Where is `geos` marked as `conda-forge`? Anything without a channel is `defaults`.

@cswartzvi I was able to import `import shapely.geometry`. Not sure what is going on with your installation. Do you have another `geos` installed and in the path?

**Comment by ocefpaf** [comment]
Also, @cswarth b/c your issue is different, please open a new issue. I'm locking this one as resolved.
